package controls

import "github.com/warrox1993/clawkwerk/internal/cyfun"

// EssentialControls = contrôles ajoutés au niveau ESSENTIAL, au-delà de
// Basic+Important. GÉNÉRÉ depuis le Self-Assessment tool ESSENTIAL du CCB
// (texte officiel). Tous déclaratifs. Questions génériques Doc/Impl.
var EssentialControls = []DeclarativeControl{
	essDecl("GV.OC-02.1", cyfun.Govern, "GV.OC", "GV.OC-02", false,
		"The organisation shall demonstrate it understands and considers the needs and expectations of both internal and external stakeholders regarding information and cybersecurity risk management.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.OC-04.3", cyfun.Govern, "GV.OC", "GV.OC-04", false,
		"Redundancy shall be implemented to meet availability requirements as defined by the organisation, legislation and/or regulations.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.OC-04.4", cyfun.Govern, "GV.OC", "GV.OC-04", false,
		"Recovery time and recovery point objectives for the resumption of essential ICT/OT system processes shall be defined and monitored.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.RR-01.1", cyfun.Govern, "GV.RR", "GV.RR-01", false,
		"The organisation's top management shall be responsible and accountable for cybersecurity risk and shall foster a culture that is risk-aware, ethical, and continually improving.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.RR-02.2", cyfun.Govern, "GV.RR", "GV.RR-02", false,
		"The organisation shall appoint a senior-level executive information security officer.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.OV-02.1", cyfun.Govern, "GV.OV", "GV.OV-02", false,
		"The information and cybersecurity risk management strategy shall be reviewed and adjusted to ensure coverage of organisational requirements and risks.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.OV-03.1", cyfun.Govern, "GV.OV", "GV.OV-03", false,
		"The organisation's cybersecurity risk management performance shall be evaluated, reviewed and adjusted when necessary.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-01.1", cyfun.Govern, "GV.SC", "GV.SC-01", false,
		"A cybersecurity supply chain risk management program, strategy, objectives, policies, and processes shall be documented, reviewed, updated when changes occur, and approved by organisational stakeholders.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-03.1", cyfun.Govern, "GV.SC", "GV.SC-03", false,
		"Information- and Cybersecurity supply chain risk management shall be integrated into information/cybersecurity and enterprise risk management, risk assessment, and improvement processes.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-05.2", cyfun.Govern, "GV.SC", "GV.SC-05", true,
		"Contractual information/cybersecurity requirements for suppliers and external partners shall be implemented to ensure a verifiable flaw resolution process and to ensure that deficiencies identified during information/cybersecurity testing and evaluation are remedied.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-05.3", cyfun.Govern, "GV.SC", "GV.SC-05", true,
		"The organisation shall establish contractual requirements permitting  the organisation to review the information/cybersecurity programmes implemented by suppliers and third-party partners.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-06.1", cyfun.Govern, "GV.SC", "GV.SC-06", false,
		"Planning and due diligence shall be carried out to reduce risks before entering into formal relationships with suppliers or other third parties.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-07.2", cyfun.Govern, "GV.SC", "GV.SC-07", false,
		"A documented list of all critical suppliers, vendors and partners of the organisation that may be involved in a major incident shall be established, kept up-to-date and made available online and off-line with due regard to confidentiality and security.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-07.3", cyfun.Govern, "GV.SC", "GV.SC-07", false,
		"The organisation shall audit business-critical third-party service providers for security compliance.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-07.4", cyfun.Govern, "GV.SC", "GV.SC-07", false,
		"The organisation shall ensure conformity with information/cybersecurity contractual obligations by suppliers and third-party partners through regular reviews of independent audits, assessments, and third party evaluations.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-09.1", cyfun.Govern, "GV.SC", "GV.SC-09", false,
		"Supply chain security practices shall be integrated into information/cybersecurity and enterprise risk management programs, and their performance shall be monitored throughout the product and service life cycle.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("GV.SC-10.1", cyfun.Govern, "GV.SC", "GV.SC-10", false,
		"Cybersecurity supply chain risk management plans shall include actions and responsibilities for managing risks that may arise after a supplier relationship or service agreement has ended.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// ID.AM-01.4 est désormais SCANNABLE (salve niches).
	// ID.AM-02.5 est désormais SCANNABLE (batch familles, réutilise une sonde).
	essDecl("ID.AM-03.3", cyfun.Identify, "ID.AM", "ID.AM-03", true,
		"The organisation's network communication and external data flows shall be mapped, documented , authorised, and updated when changes occur.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.AM-04.2", cyfun.Identify, "ID.AM", "ID.AM-04", false,
		"The organisation shall map, document and authorise the flow of information to/from external systems and update the flow when changes occur.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.AM-08.5", cyfun.Identify, "ID.AM", "ID.AM-08", false,
		"The organisation shall ensure that disposal actions are approved, tracked, documented, and verified.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.AM-08.7", cyfun.Identify, "ID.AM", "ID.AM-08", true,
		"The organisation shall prevent unauthorised removal of maintenance equipment which contains critical system information of the organisation.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.AM-08.9", cyfun.Identify, "ID.AM", "ID.AM-08", true,
		"Maintenance tools and portable storage devices shall be inspected as they enter the facility and shall be protected by anti-malware solutions that scan them for malicious code before they are used on the organisation's systems.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.AM-08.10", cyfun.Identify, "ID.AM", "ID.AM-08", true,
		"The organisation shall verify security controls following maintenance or repairs/patching, and take action as appropriate.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.AM-08.13", cyfun.Identify, "ID.AM", "ID.AM-08", false,
		"The organisation shall require remote maintenance diagnostic services to be performed from a system that implements security features similar to the security features implemented on the equivalent organisation's critical system.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.RA-01.4", cyfun.Identify, "ID.RA", "ID.RA-01", false,
		"To ensure that organisation's operations are not adversely affected by the testing process, performance/load testing and penetration testing on the organisation’s systems shall be carried out with care.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.RA-02.2", cyfun.Identify, "ID.RA", "ID.RA-02", false,
		"Automated mechanisms shall be implemented to disseminate security alerts and advisories to relevant organisation stakeholders.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.RA-05.3", cyfun.Identify, "ID.RA", "ID.RA-05", false,
		"Risk assessment results shall be disseminated to relevant stakeholders.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// ID.RA-08.2 est désormais SCANNABLE (salve niches).
	essDecl("ID.IM-03.7", cyfun.Identify, "ID.IM", "ID.IM-03", false,
		"The organisation shall implement independent teams to assess its processes, best practices, and technology solutions to safeguard critical systems and assets.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("ID.IM-03.8", cyfun.Identify, "ID.IM", "ID.IM-03", false,
		"The organisation shall ensure that the security plan for its critical systems facilitates the review, testing, and continual improvement of the security protection processes.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// ID.IM-03.9 est désormais SCANNABLE (salve niches).
	essDecl("ID.IM-04.2", cyfun.Identify, "ID.IM", "ID.IM-04", false,
		"The organisation shall coordinate the development and testing of Incident Response Plans and other cybersecurity plans that affect operations with stakeholders to ensure that these plans align with overall organisational goals and enhance resilience.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.AA-01.3 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// PR.AA-01.4 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	essDecl("PR.AA-01.5", cyfun.Protect, "PR.AA", "PR.AA-01", false,
		"The organisation’s critical systems shall be monitored for atypical use of system credentials. Credentials associated with significant risk shall be disabled.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.AA-02.2 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// PR.AA-03.4 est désormais SCANNABLE (batch familles, réutilise une sonde).
	essDecl("PR.AA-03.5", cyfun.Protect, "PR.AA", "PR.AA-03", false,
		"The security for connections with external systems shall be verified and framed by documented agreements.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.AA-04.1", cyfun.Protect, "PR.AA", "PR.AA-04", false,
		"Identity assertions shall be protected, conveyed, and verified.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.AA-05.8", cyfun.Protect, "PR.AA", "PR.AA-05", false,
		"Account usage restrictions for specific time periods and locations shall be taken into account in the organisation's security access policy and applied accordingly.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.AA-05.9 est désormais SCANNABLE (batch familles, réutilise une sonde).
	essDecl("PR.AA-06.3", cyfun.Protect, "PR.AA", "PR.AA-06", false,
		"Critical zones shall have additional physical access controls beyond those applied to general facilities.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.AA-06.4", cyfun.Protect, "PR.AA", "PR.AA-06", false,
		"Assets located within critical zones shall be physically protected against unauthorised access, damage, or interference.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.AT-01.4", cyfun.Protect, "PR.AT", "PR.AT-01", false,
		"The organisation shall evaluate whether its cybersecurity awareness training is effective in improving knowledge, behaviour, and readiness across the organisation.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.DS-01.2 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// PR.DS-01.3 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// PR.DS-01.6 est désormais SCANNABLE (sonde neuve).
	// PR.DS-02.1 est désormais SCANNABLE (sonde neuve).
	// PR.DS-02.2 est désormais SCANNABLE (sonde neuve).
	essDecl("PR.DS-10.1", cyfun.Protect, "PR.DS", "PR.DS-10", false,
		"The organisation’s critical systems shall be protected against denial-of-service attacks or at least the effect of such attacks shall be limited.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.DS-11.4", cyfun.Protect, "PR.DS", "PR.DS-11", false,
		"The organisation shall regularly verify the integrity and recoverability of backups through coordinated testing with all relevant continuity and incident response functions. Backup testing shall be integrated into broader resilience planning, including business continuity, disaster recovery, and cyber incident response.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.DS-11.5", cyfun.Protect, "PR.DS", "PR.DS-11", false,
		"Backups of critical systems (such as operating systems, configurations, and applications) shall be kept separate from backups of critical information (such as business data, documents, and databases) to support faster and more reliable recovery.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.PS-01.2 et PR.PS-01.3 sont désormais SCANNABLES (famille durcissement, voir
	// durcissement.go + engine.EssentialScannables).
	// PR.PS-01.4 est désormais SCANNABLE (sonde neuve).
	essDecl("PR.PS-01.5", cyfun.Protect, "PR.PS", "PR.PS-01", false,
		"Unauthorised configuration changes to organisation's systems shall be monitored and addressed with the appropriate mitigation actions.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.PS-04.4 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	essDecl("PR.PS-04.5", cyfun.Protect, "PR.PS", "PR.PS-04", false,
		"The organisation shall ensure that authorised personnel can extend or enhance audit logging and monitoring capabilities when needed to support investigations or incident response.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.PS-06.3", cyfun.Protect, "PR.PS", "PR.PS-06", false,
		"Secure software development practices shall be integrated into all phases of the software development lifecycle, and their effectiveness shall be regularly monitored and improved.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.PS-06.4", cyfun.Protect, "PR.PS", "PR.PS-06", false,
		"For planned changes to the organisation's critical systems, a security impact analysis shall be performed in a separate test environment before implementation in an operational environment.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.IR-01.5", cyfun.Protect, "PR.IR", "PR.IR-01", false,
		"The organisation shall implement, where feasible, authenticated proxy servers or firewalls with URL filtering and threat intelligence capabilities for defined communications traffic between its critical systems and external networks.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.IR-01.6", cyfun.Protect, "PR.IR", "PR.IR-01", false,
		"The organisation shall ensure that its critical systems are designed to fail securely and remain protected in the event of an operational failure of a border protection device.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.IR-01.7", cyfun.Protect, "PR.IR", "PR.IR-01", false,
		"The organisation shall ensure that development and test environments are strictly separated from the production environment, particularly in ICS/OT systems where any crossover could compromise safety, endanger health, or disrupt essential operations.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.IR-01.8", cyfun.Protect, "PR.IR", "PR.IR-01", false,
		"The organisation shall define, monitor, and control the flow of information and data within and between its critical systems to ensure that only authorised and secure exchanges occur, regardless of network boundaries or system architecture.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.IR-01.9", cyfun.Protect, "PR.IR", "PR.IR-01", false,
		"The organisation shall manage interfaces with external telecommunications services as part of its broader network security policy, by defining how traffic is controlled, ensuring the confidentiality and integrity of transmitted information, and reviewing and documenting any exceptions to established rules.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.IR-02.2", cyfun.Protect, "PR.IR", "PR.IR-02", false,
		"The organisation shall implement fire detection devices that activate and notify key personnel automatically in the event of a fire.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("PR.IR-03.1", cyfun.Protect, "PR.IR", "PR.IR-03", false,
		"The organisation shall implement mechanisms to ensure that critical systems and services remain operational or can be quickly restored during both normal operations and adverse conditions.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("DE.CM-01.4", cyfun.Detect, "DE.CM", "DE.CM-01", false,
		"The organisation shall continuously monitor its network to spot signs of cyber threats or unusual activity, using clearly defined rules for what counts as a potential security incident.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("DE.CM-02.2", cyfun.Detect, "DE.CM", "DE.CM-02", false,
		"Physical access to the organisation's critical systems and devices, in addition to physical access monitoring to the facility, shall be supplemented by physical intrusion alarms, surveillance equipment, and independent monitoring teams.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("DE.CM-09.2", cyfun.Detect, "DE.CM", "DE.CM-09", false,
		"The organisation shall implement hardware integrity checks to detect unauthorised tampering of critical system hardware. Controls shall be proportionate to the organisation’s risk profile and operational capacity.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("DE.CM-09.3", cyfun.Detect, "DE.CM", "DE.CM-09", false,
		"The organisation's incident response plan shall include measures to detect unauthorised tampering with the hardware of critical systems.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// DE.CM-09.4 est désormais SCANNABLE (batch familles, réutilise une sonde).
	// DE.AE-02.2 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// DE.AE-03.3 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	essDecl("DE.AE-04.1", cyfun.Detect, "DE.AE", "DE.AE-04", false,
		"The organisation shall assess the negative impacts of detected events on its operations, assets, and individuals, and shall link these impacts to the results of its risk assessments.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// RS.MA-02.2 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	essDecl("RS.AN-03.1", cyfun.Respond, "RS.AN", "RS.AN-03", false,
		"Each incident shall be analysed to determine what occurred and to identify its root cause.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("RS.AN-06.1", cyfun.Respond, "RS.AN", "RS.AN-06", false,
		"Actions performed during an investigation shall be recorded, and the records' integrity and provenance shall be preserved.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("RS.AN-07.1", cyfun.Respond, "RS.AN", "RS.AN-07", false,
		"Incident data and metadata shall be collected and protected to ensure their accuracy, authenticity, and traceability.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("RS.AN-08.1", cyfun.Respond, "RS.AN", "RS.AN-08", false,
		"An incident’s magnitude shall be estimated and validated.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("RC.RP-02.1", cyfun.Recover, "RC.RP", "RC.RP-02", false,
		"The organisation's essential functions and services shall be continued with little or no loss of operational continuity, and continuity shall be maintained until full system recovery.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("RC.CO-04.2", cyfun.Recover, "RC.CO", "RC.CO-04", false,
		"The organisation shall assign a Public Relations Officer (PRO) to manage public communications during information/cybersecurity incident recovery, ensuring that public updates are shared while maintaining the confidentiality, integrity, and accuracy of the information.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	essDecl("RC.CO-04.3", cyfun.Recover, "RC.CO", "RC.CO-04", false,
		"The organisation shall implement a crisis communication strategy to mitigate negative impacts during a crisis and help restore its reputation afterward.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
}
