package controls

import "github.com/warrox1993/clawkwerk/internal/cyfun"

// ImportantControls = contrôles ajoutés au niveau IMPORTANT (99), au-delà des
// 34 Basic. GÉNÉRÉ depuis le Self-Assessment tool IMPORTANT du CCB (texte
// officiel). Tous déclaratifs (organisationnels) ; les 7 contrôles scannables
// Basic s'appliquent aussi à IMPORTANT. Questions génériques Doc/Impl.
var ImportantControls = []DeclarativeControl{
	impDecl("GV.OC-01.1", cyfun.Govern, "GV.OC", "GV.OC-01", false,
		"The organisation's mission shall be established, communicated and shall form the basis for information and cybersecurity risk management.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.OC-03.2", cyfun.Govern, "GV.OC", "GV.OC-03", false,
		"Legal and regulatory obligations related to information and cybersecurity shall be continuously managed to ensure they remain accurate, up to date, and effectively applied.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.OC-04.1", cyfun.Govern, "GV.OC", "GV.OC-04", false,
		"The organisation shall identify, document, and communicate the critical objectives, capabilities, and services relied upon by external stakeholders, prioritise them based on criticality, and integrate this prioritisation into the risk assessment process.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.OC-04.2", cyfun.Govern, "GV.OC", "GV.OC-04", false,
		"The organisation shall define and document cybersecurity requirements for essential operations, validate them through testing and audits, keep records of results and corrective actions, and regularly update requirements based on evolving risks.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.OC-05.1", cyfun.Govern, "GV.OC", "GV.OC-05", false,
		"The organisation shall identify, document, and communicate its role in the supply chain, including the external capabilities, services, and dependencies it relies on (upstream), as well as its interactions with downstream stakeholders..",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RM-01.1", cyfun.Govern, "GV.RM", "GV.RM-01", false,
		"Information and cybersecurity objectives shall be coherently established throughout the organisation and approved by senior management.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RM-02.1", cyfun.Govern, "GV.RM", "GV.RM-02", false,
		"Risk appetite and risk tolerance statements shall be defined, documented, approved by senior management, communicated, and maintained.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RM-03.2", cyfun.Govern, "GV.RM", "GV.RM-03", false,
		"Information and cybersecurity risks shall be documented, as part of the enterprise risk management processes, formally approved by senior management, and updated when changes occur.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RM-04.1", cyfun.Govern, "GV.RM", "GV.RM-04", false,
		"A high-level plan or vision shall be formally established and clearly communicated to everyone involved on how to manage risks, including the different strategies the organisation can employ to deal with identified risks based on risk appetite or risk tolerance level.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RM-05.1", cyfun.Govern, "GV.RM", "GV.RM-05", false,
		"To support the high-level risk management vision, the organisation shall establish clear lines of communication for cybersecurity risks, including those arising from suppliers and third parties.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RR-02.1", cyfun.Govern, "GV.RR", "GV.RR-02", true,
		"Information security and cyber security roles, responsibilities and authorities for employees, suppliers, customers, and partners shall be documented, reviewed, authorised, kept up-to-date, communicated, and coordinated internally and externally.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RR-03.1", cyfun.Govern, "GV.RR", "GV.RR-03", false,
		"Sufficient resources shall be allocated in line with the cybersecurity risk strategy, roles, responsibilities and policies.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RR-03.2", cyfun.Govern, "GV.RR", "GV.RR-03", false,
		"The organisation shall assign roles and responsibilities for reviewing and updating response and recovery plans, ensuring they reflect changes in the risk environment and remain effective.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.RR-04.2", cyfun.Govern, "GV.RR", "GV.RR-04", false,
		"A cybersecurity process for human resources shall be developed and maintained applicable at recruitment, during employment and at termination of employment.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.PO-01.2", cyfun.Govern, "GV.PO", "GV.PO-01", false,
		"Organisational-wide information and cybersecurity policies and procedures shall include the use of cryptography and, where appropriate, encryption, reflect changes in requirements, threats, technology and organisational roles, and be approved by senior management, who oversee implementation.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.SC-02.1", cyfun.Govern, "GV.SC", "GV.SC-02", false,
		"Third-party providers shall notify any transfer, termination or transition of personnel with physical or logical access to business-critical system elements of the organisation.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.SC-05.1", cyfun.Govern, "GV.SC", "GV.SC-05", false,
		"Requirements for addressing cybersecurity risks and the sharing of sensitive information in supply chains shall be established, prioritised, integrated into contracts and other types of formal agreements, and enforced.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.SC-07.1", cyfun.Govern, "GV.SC", "GV.SC-07", false,
		"The risks posed by a supplier, its products and services and other third parties shall be identified, documented, prioritised, mitigated and assessed at least annually and when changes occur during the relationship.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("GV.SC-08.1", cyfun.Govern, "GV.SC", "GV.SC-08", false,
		"The organisation shall identify and document key personnel from relevant suppliers and other third parties to include them in incident planning, response, and recovery activities.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// ID.AM-01.2 est désormais SCANNABLE (salve niches).
	// ID.AM-01.3 est désormais SCANNABLE (salve niches).
	// ID.AM-02.2 est désormais SCANNABLE (batch familles, réutilise une sonde).
	impDecl("ID.AM-02.3", cyfun.Identify, "ID.AM", "ID.AM-02", false,
		"The people responsible and accountable for managing software platforms and applications within the organisation shall be formally identified.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// ID.AM-02.4 est désormais SCANNABLE (batch familles, réutilise une sonde).
	impDecl("ID.AM-03-2", cyfun.Identify, "ID.AM", "ID.AM-03", false, // sous-catégorie ID.AM-03 (l'ID d'exigence garde l'écriture du CCB)
		"The organisation's network communication and internal data flows shall be mapped, documented, authorised, and updated when changes occur.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.AM-04.1", cyfun.Identify, "ID.AM", "ID.AM-04", false,
		"Organisations shall keep a clear and up-to-date list of all external services it uses, including how they connect to their systems. These services shall be reviewed and approved before use, and the list shall be updated whenever changes happen.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.AM-07.2", cyfun.Identify, "ID.AM", "ID.AM-07", false,
		"Inventories of data and associated metadata shall be maintained for designated data types.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.AM-08.3", cyfun.Identify, "ID.AM", "ID.AM-08", false,
		"The organisation shall enforce accountability for all its business-critical assets throughout the system lifecycle, including removal, transfers, and disposal.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.AM-08.4", cyfun.Identify, "ID.AM", "ID.AM-08", false,
		"The organisation shall ensure that the necessary measures are taken to deal with loss, misuse, damage, or theft of assets.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.AM-08.6", cyfun.Identify, "ID.AM", "ID.AM-08", false,
		"The organisation shall plan, perform and document preventive maintenance and repairs on its critical system components according to approved processes and tools.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.AM-08.8", cyfun.Identify, "ID.AM", "ID.AM-08", false,
		"The organisation shall pre-approve, monitor and enforce maintenance tools for use on its critical systems.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.AM-08.11", cyfun.Identify, "ID.AM", "ID.AM-08", false,
		"Remote maintenance and diagnostic activities of organisational assets shall be pre-approved and the performance logged.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// ID.AM-08.12 est désormais SCANNABLE (batch familles, réutilise une sonde).
	// ID.RA-01.2 est désormais SCANNABLE (batch familles, réutilise une sonde).
	impDecl("ID.RA-01.3", cyfun.Identify, "ID.RA", "ID.RA-01", false,
		"The organisation shall establish and maintain a documented process that enables continuous review, analysis and remediation of vulnerabilities and provides for information sharing where applicable.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.RA-01.5", cyfun.Identify, "ID.RA", "ID.RA-01", false,
		"Vulnerability scanning shall not adversely impact system functions.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// ID.RA-01.6 est désormais SCANNABLE (batch familles, réutilise une sonde).
	impDecl("ID.RA-02.1", cyfun.Identify, "ID.RA", "ID.RA-02", false,
		"A threat and vulnerability awareness programme that includes a cross-organisation information-sharing capability shall be implemented.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.RA-03.1", cyfun.Identify, "ID.RA", "ID.RA-03", false,
		"Threats shall be identified and assessed in relation to all relevant assets, including software, network and system architectures, and facilities.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.RA-05.2", cyfun.Identify, "ID.RA", "ID.RA-05", false,
		"The organisation shall conduct and document risk assessments in which risk is determined by threats, vulnerabilities, impact on business processes and assets, and likelihood of their occurrence.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.RA-06.1", cyfun.Identify, "ID.RA", "ID.RA-06", false,
		"Risk responses shall be identified, prioritised, planned, tracked and communicated.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.RA-08.1", cyfun.Identify, "ID.RA", "ID.RA-08", true,
		"The organisation shall establish and implement a vulnerability management plan to identify, analyse, assess, mitigate and communicate all types of vulnerabilities including in the form of a Coordinated Vulnerability Disclosure (CVD) according to applicable legal modalities.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.IM-02.1", cyfun.Identify, "ID.IM", "ID.IM-02", false,
		"Security tests and exercises, including those conducted with suppliers and relevant third parties, shall be used to identify areas for improvement.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.IM-03.2", cyfun.Identify, "ID.IM", "ID.IM-03", false,
		"The organisation shall incorporate lessons learned from incident handling activities into updated or new incident handling processes and/or procedures that are framed by appropriate training after review, approval and testing.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.IM-03.3", cyfun.Identify, "ID.IM", "ID.IM-03", false,
		"The organisation shall identify improvements derived from the monitoring, measurements, assessments, and lessons learned and consequently translate this into improved processes / procedures / technologies to enhance its cyber resilience (continuous improvement).",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.IM-03.4", cyfun.Identify, "ID.IM", "ID.IM-03", false,
		"The organisation shall collaborate and share information about its critical system's related security incidents and mitigation measures with designated partners.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.IM-03.5", cyfun.Identify, "ID.IM", "ID.IM-03", false,
		"Communication of effectiveness of protection technologies shall be shared with relevant stakeholders.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.IM-03.6", cyfun.Identify, "ID.IM", "ID.IM-03", false,
		"The organisation shall implement, where feasible, automated mechanisms to facilitate the process of information sharing and collaboration.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("ID.IM-04.1", cyfun.Identify, "ID.IM", "ID.IM-04", false,
		"Contingency and continuity plans shall be established, communicated, maintained, tested, validated, and improved.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.AA-01.2 est désormais SCANNABLE (salve niches).
	impDecl("PR.AA-02.1", cyfun.Protect, "PR.AA", "PR.AA-02", false,
		"The organisation shall implement documented procedures for verifying the identity of individuals before issuing credentials that provide access to the organisation's systems.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.AA-03.3 est désormais SCANNABLE (batch familles, réutilise une sonde).
	// PR.AA-05.5 est désormais SCANNABLE (salve niches).
	impDecl("PR.AA-05.6", cyfun.Protect, "PR.AA", "PR.AA-05", false,
		"Separation of duties (SoD) shall be ensured in the management of access rights.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.AA-05.7 est désormais SCANNABLE (batch familles, réutilise une sonde).
	impDecl("PR.AA-06.2", cyfun.Protect, "PR.AA", "PR.AA-06", false,
		"Physical access controls shall include specific procedures for emergency situations, ensuring continued protection of critical and non-critical assets during such events.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.AT-01.2", cyfun.Protect, "PR.AT", "PR.AT-01", false,
		"The organisation shall include insider threat awareness and reporting in its cybersecurity training to help personnel recognise and respond to potential internal risks.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.AT-01.3", cyfun.Protect, "PR.AT", "PR.AT-01", false,
		"Personnel shall receive training to understand their specific roles, responsibilities, and priorities during a cybersecurity or information security incident, including the steps they need to follow to respond effectively.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.AT-02.1", cyfun.Protect, "PR.AT", "PR.AT-02", false,
		"Members of management bodies shall be able to demonstrate that they have completed training that gives them a solid understanding of information and cybersecurity and risk management so that they can assess information and cyber security risks and their consequences and propose the necessary risk mitigation, considering their roles, responsibilities and authorities.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.AT-02.2", cyfun.Protect, "PR.AT", "PR.AT-02", false,
		"Individuals in specialised roles shall be provided with awareness and training before privileges are granted, so that they possess the knowledge and skills to perform relevant tasks with cybersecurity risks in mind.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.AT-02.3", cyfun.Protect, "PR.AT", "PR.AT-02", false,
		"Privileged users shall be qualified before privileges are granted, and these users shall be able to demonstrate the understanding of their roles, responsibilities, and authorities.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.DS-01.1 est désormais SCANNABLE (sonde neuve).
	// PR.DS-01.4 est désormais SCANNABLE (sonde neuve).
	// PR.DS-01.5 est désormais SCANNABLE (sonde neuve).
	// PR.DS-11.2 est désormais SCANNABLE (batch familles, réutilise une sonde).
	// PR.DS-11.3 est désormais SCANNABLE (batch familles, réutilise une sonde).
	// PR.PS-01.1 est désormais SCANNABLE (famille durcissement, voir durcissement.go
	// + engine.ImportantScannables).
	// PR.PS-02.1 est désormais SCANNABLE (sonde neuve).
	impDecl("PR.PS-03.1", cyfun.Protect, "PR.PS", "PR.PS-03", false,
		"Hardware used in business-critical environments shall be maintained, replaced, or removed based on its associated security and operational risk.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.PS-04.2 est désormais SCANNABLE (sonde neuve).
	// PR.PS-04.3 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// PR.PS-05.2 est désormais SCANNABLE (sonde neuve).
	impDecl("PR.PS-06.1", cyfun.Protect, "PR.PS", "PR.PS-06", false,
		"Security shall be considered throughout the lifecycle of systems and applications, whether developed internally or acquired externally.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.PS-06.2", cyfun.Protect, "PR.PS", "PR.PS-06", false,
		"Changes and exceptions shall be tested and validated before being implemented into operational systems.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.IR-01.3", cyfun.Protect, "PR.IR", "PR.IR-01", true,
		"To ensure operational stability and security, the organisation shall, without exception, identify, document, and control connections between components of its critical systems.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.IR-01.4", cyfun.Protect, "PR.IR", "PR.IR-01", true,
		"The organisation shall implement appropriate boundary protection measures to monitor and control communications at external and key internal boundaries of its critical systems, across both IT and OT environments, to ensure secure and reliable operations.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("PR.IR-02.1", cyfun.Protect, "PR.IR", "PR.IR-02", false,
		"The organisation shall define, implement and maintain policies and procedures related to emergency and safety systems, fire protection systems and environmental controls for its critical systems.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// PR.IR-04.1 est désormais SCANNABLE (salve niches).
	// DE.CM-01.3 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	impDecl("DE.CM-02.1", cyfun.Detect, "DE.CM", "DE.CM-02", false,
		"The physical environment shall be monitored to find potentially adverse events.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// DE.CM-03.2 est désormais SCANNABLE (batch familles, réutilise une sonde).
	impDecl("DE.CM-06.1", cyfun.Detect, "DE.CM", "DE.CM-06", false,
		"External service provider activities and services shall be secured and monitored to find potentially adverse events.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("DE.CM-06.2", cyfun.Detect, "DE.CM", "DE.CM-06", false,
		"External service providers' conformance with personnel security policies and procedures and contract security requirements shall be monitored relative to their cybersecurity risks.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// DE.CM-09.1 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// DE.AE-02.1 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	// DE.AE-03.2 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	impDecl("DE.AE-06.1", cyfun.Detect, "DE.AE", "DE.AE-06", false,
		"Information about adverse events shall be promptly delivered to authorised personnel and systems to enable timely detection, investigation, and response.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("DE.AE-08.1", cyfun.Detect, "DE.AE", "DE.AE-08", false,
		"Incidents shall be reported when adverse events meet defined and documented incident criteria.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RS.MA-01.2", cyfun.Respond, "RS.MA", "RS.MA-01", false,
		"The organisation shall coordinate information/cybersecurity incident response actions with all predefined stakeholders.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RS.MA-02.1", cyfun.Respond, "RS.MA", "RS.MA-02", false,
		"Information/cybersecurity incident reports shall be triaged and validated in accordance with the organisation’s incident response procedures.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RS.MA-03.1", cyfun.Respond, "RS.MA", "RS.MA-03", false,
		"Information/cybersecurity incidents shall be categorised, prioritised and escalated as specified in the incident response plan.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RS.MA-05.1", cyfun.Respond, "RS.MA", "RS.MA-05", false,
		"Clear criteria shall be defined and applied to determine when incident recovery processes need to be initiated.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RS.CO-02.2", cyfun.Respond, "RS.CO", "RS.CO-02", true,
		"Cybersecurity incidents shall be shared with relevant external stakeholders within the timeframes defined in the Incident Response Plan, including reporting significant incidents to authorities as required by law.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RS.MI-01.1", cyfun.Respond, "RS.MI", "RS.MI-01", false,
		"Cybersecurity incidents shall be contained and eliminated. Any decision to accept and retain certain cybersecurity risks shall be formally documented.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	// RS.MI-01.2 est désormais SCANNABLE (salve journalisation/identités/FIM/détection).
	impDecl("RC.RP-05.1", cyfun.Recover, "RC.RP", "RC.RP-05", false,
		"The integrity of restored systems and assets shall be verified before they are returned to service. Systems and services shall be fully restored, and normal operations shall be confirmed.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RC.RP-06.1", cyfun.Recover, "RC.RP", "RC.RP-06", false,
		"The end of incident recovery shall be formally declared based on predefined criteria, and all incident-related documentation shall be completed and reviewed.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RC.CO-03.1", cyfun.Recover, "RC.CO", "RC.CO-03", false,
		"Recovery activities and progress in restoring operational capabilities shall be communicated to designated internal and external stakeholders in accordance with established communication procedures.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
	impDecl("RC.CO-04.1", cyfun.Recover, "RC.CO", "RC.CO-04", false,
		"Public updates on incident recovery shall be shared using approved communication methods and messaging, in accordance with established procedures.",
		"L'exigence est-elle documentée (politique/procédure écrite, approuvée et revue) ?",
		"Est-elle appliquée et vérifiée dans les faits ?"),
}
